name: Safe Deploy via FTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List workspace
        run: |
          echo "Workspace path: ${{ github.workspace }}"
          ls -R ${{ github.workspace }}

      - name: FTP Deploy (dry-run)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}

          # workspace 直下のファイル・フォルダをアップロード
          local-dir: ${{ github.workspace }}/

          server-dir: /public_html/luful-life.com/
          dangerous-clean-slate: false
          dry-run: false
          log-level: standard

           # .github フォルダはアップロード対象から除外
          exclude: |
            .github/**
